### ISSUE TITLE
Number of fSNPs greater that the specified with -m

### ISSUE THREAD

**Issue by gouthamatla** [natsuhiko/rasqual#14]
I am getting this error

> The number of fSNPs is greater than that specified by '-m' option.

I would like to know how RASQUAL determines the number of fSNPs. I calculated the fSNPs as the ones that overlaps the exons of that gene.

**Comment by natsuhiko** [comment]
RASQUAL discards a part of fSNPs which are less covered by sequenced reads. However the number never exceeds the number of SNPs overlapping exons (specified by -m). If you can provide us your data we can further investigate what happened in your data.

Best regards,
Natsuhiko

**Comment by gouthamatla** [comment]
Sorry. I solved it. I was not providing proper start and end coordinates of exons. Its working fine now.
