### ISSUE TITLE
Meta analysis of RASQUAL results from different datasets

### ISSUE THREAD

**Issue by gouthamatla** [natsuhiko/rasqual#16]
Hi, I am looking for any recommendations to perform a meta analysis from RASQUAL considering effect size and p-values,  from different studies. Its the same tissue but from different consortiums.

**Comment by natsuhiko** [comment]
I have no preference on doing a meta-analysis with RASQUAL p-values. You could use anything, for example, metap package on R?

**Comment by kwcurrin** [comment]
Along these lines, how do we determine the direction of effect in RASQUAL? The effect sizes all appear positive, so is it necessary to use external information to determine if the alternate allele increases or decreases expression? Thanks!

**Comment by natsuhiko** [comment]
If the PI value (column 12) is greater than 0.5, the alternative allele in the VCF file is the increasing allele, otherwise the reference allele is the increasing allele of the feature coverage. Note that PI=0.5 is the null.

Best regards,
Natsuhiko
