### ISSUE TITLE
"nan" for squared correlation between prior and posterior genotypes (fSNPs)

### ISSUE THREAD

**Issue by gouthamatla** [natsuhiko/rasqual#17]
Hi Natsuhiko,

I ran RASQUAL on ATAC-Seq data to get the lead SNP per peak. Out of 121,214 peaks I analyzed, 54,232 snps have -nan in the 24th column, `Squared correlation between prior and posterior genotypes (fSNPs)` . Is it because those SNPs are not fSNPs but rSNPs ?

Thanks,
Goutham A

**Comment by natsuhiko** [comment]
Hi Goutham,

If there is no fSNP within the feature, the 24th column becomes NA.

Best regards,
Natsuhiko

**Comment by gouthamatla** [comment]
Thanks Natsuhiko for quick reply.
