### ISSUE TITLE
Get p-value for each feature-variant test 

### ISSUE THREAD

**Issue by liangyy** [natsuhiko/rasqual#22]
Hi Natsuhiko,

I have a question about obtaining the raw p-value of the test. I am not sure if the q-value reported is always done by permutation. I am wondering if it is possible to get the raw p-value of each test (and presumably shut down permutation since it is not necessary for this setting).

Thank you very much!

Yanyu

**Comment by natsuhiko** [comment]
Hi Yanyu,

The Q-value is based on the Benjamini-Hochberg method, but not permutation. This is adjusting multiple testing for each feature. 

Best regards,
Natsuhiko

**Comment by liangyy** [comment]
Hi Natsuhiko,

Thanks for your explanation! I am wondering if `rasqual` can output raw p-value w/o transforming it to q-value. If not, can I do something like `p.val = q.val * rank(q.val, ties.method = 'max') / length(q.val)` to get a rough estimate on p-value (I guess it is upper bound of p-value)?

Thanks!

Yanyu

**Comment by natsuhiko** [comment]
Hi Yanyu,

You can calculate the p-value from the chi-square statistic on the 11th column of the output, e.g., pchisq(col11, 1, lower=F) on R.

Best regards,
Natsuhiko

**Comment by liangyy** [comment]
Hi Natsuhiko,

Thanks for the clarification! I will close the issue.

Yanyu

**Comment by kwcurrin** [comment]
A followup on this, when pchisq(col11,1,lower=F) is used to get p-values, do these p-values need to be multiplied by 2 before multiple testing correction?

**Comment by kwcurrin** [comment]
Thanks for your helpful (and quick) reply
