### ISSUE TITLE
Minor allele frequency filtering

### ISSUE THREAD

**Issue by kwcurrin** [natsuhiko/rasqual#25]
Hello,

For minor allele frequency filtering with -a/--minor-allele-frequency, does RASQUAL calculate the minor allele frequency or just take it from the VCF info file? I have some VCF files where I have removed a few individuals, so the MAF in the info field is not correct for the new set of samples. If RASQUAL takes MAF from info, then I will need to make a new set of VCFs when subsetting samples.

Thanks!

Kevin

**Comment by kwcurrin** [comment]
Sory, I meant "info field" of VCF, not "info file"

**Comment by natsuhiko** [comment]
Hi Kevin,

RASQUAL directory calculates MAF from genotype dosage and doesn't use INFO field.

Best regards,
Natsuhiko

**Comment by kwcurrin** [comment]
Great! Thanks!
