### ISSUE TITLE
Number of test SNPs

### ISSUE THREAD

**Issue by raehoon3415** [natsuhiko/rasqual#29]
Dear Natsuhiko,

When I run the sample code (after removing -t option to print all summary statistics)
`tabix data/chr11.gz 11:2315000-2340000 | bin/rasqual -y data/Y.bin -k data/K.bin -n 24 -j 1 -l 378 -m 62     -s 2316875,2320655,2321750,2321914,2324112 -e 2319151,2320937,2321843,2323290,2324279    -f C11orf21 -z`
I get 83 lines rather than 378 SNPs that are tested.

`tabix data/chr11.gz 11:2315000-2340000 | wc -l`
returns 378 for me.

I get some SNPs dropped in the results when I run my data on it, as well.

Is this expected?

**Comment by natsuhiko** [comment]
Hi,

The number of testing SNPs (-l option) is used to allocate memory for the input (378 lines from VCF file). RASQUAL internally filters out SNPs with low minor allele frequency, low imputation quality score and so on, before actually testing them. Please take a look at the explanation of RASQUAL options by just typing bin/rasqual on the command line.

Best regards,
Natsuhiko

**Comment by raehoon3415** [comment]
Dear Natsuhiko,

Thank you for such a quick reply.
I suspect that is what's happening.
When I loosen the rSNP filter options, the number of lines increase (though not quite to 378).

I will close this issue.

Best,

Raehoon.
