### ISSUE TITLE
MAF filtering with -a uses > rather than >= 

### ISSUE THREAD

**Issue by kwcurrin** [natsuhiko/rasqual#34]
Hello,

When setting -a to 0.1 to get MAF >= 10%, the smallest and largest allele frequencies in my RASQUAL output files are 0.125 and 0.875, indicating that the MAF is 0.125. I have 20 samples, so 0.125 is the next highest MAF after 0.1. Would it be possible to change -a to select >= value rather than > value? Alternatively, updating the documentation to suggest using a value slightly lower than the target MAF could be a good work around. For example, -a 0.099 if 0.1 is required.

Thanks!

Kevin

**Comment by natsuhiko** [comment]
Hi Kevin,

Thanks for pointing out. I updated the code.

Best regards,
Natsuhiko
