### ISSUE TITLE
Do covariates need to be normalized? 

### ISSUE THREAD

**Issue by iamjli** [natsuhiko/rasqual#38]
Can they take all positive values for instance? 

Also, if we want to model a categorical variable, say male/female, can this be accomplished by just assigning 0/1s? 

Thanks,
Johnny

**Comment by natsuhiko** [comment]
Hi Johnny,

The raw counts are adjusted by covariates in the log scale, like the standard poisson linear regression with log link function. You can use any covariate, both numerical and categorical variables appropriately converted into dummy variables.

Best regards,
Natsuhiko
