### ISSUE TITLE
createASVCF.sh with 10X Genomics single cell bams

### ISSUE THREAD

**Issue by adamturner1** [natsuhiko/rasqual#45]
Hi Natsuhiko,

I have a question about using RASQUAL with 10X Genomics bam files. Specifically I am having issues at the createASVCF.sh step to create the allele specific vcf file. I have previously gotten this to work for 25 bulk ATAC-seq files. My output of this step normally looks like this:
![bulk](https://user-images.githubusercontent.com/35438715/101807676-62880280-3ae3-11eb-9fc8-a9f1379df649.png)

I am now running createASVCF.sh on 40 single cell bam files generated using 10X Cell Ranger ATAC. bam files were extracted for each cell type. When I run this I keep getting core dumps and segmentation faults and traced this back to the qcFilterBam step. Instead of getting reads found, reads removed, and reads remaining printed there are continuous core dumps. My recent output looks like this with the single cell bam files:
![singlecell](https://user-images.githubusercontent.com/35438715/101808913-ebec0480-3ae4-11eb-8cb7-434e1d2c0160.png)

I have used very large amounts of memory but keep getting segmentation faults at the qcFilterBam step. Also, the single cell bam files look normal and work with programs such as samtools. Do you have any suggestions how I can address this?

Thank you very much,
Adam

**Comment by natsuhiko** [comment]
Hi Adam,

I'm sorry, it is likely to be due to a bug of qcFilterBam. I think the sequencing tags created by CellRanger are invalid. Can you upload a sam file of several sequenced reads to check the tags?

Best regards,
Natsuhiko

**Comment by adamturner1** [comment]
Hi Natsuhiko,

Below is an image of several sequencing reads generated by 10X Cell Ranger ATAC:

<img width="2030" alt="image" src="https://user-images.githubusercontent.com/35438715/101831018-60ce3700-3b03-11eb-929c-ad194442e093.png">

Best,
Adam

**Comment by alperoglu** [comment]
Hi, I was wondering if there were any updates to this issue. I'm having the same problem with sequencing files from 10x's cellranger atac.

Thank you,
Alper

**Comment by natsuhiko** [comment]
Hi Alper,

I modified a definition of memory allocation. Could you download qcFilterBam.c and qcFilterBam.h and compile them again?

If this doesn't help, I need the whole bam file to investigate.

Sorry for the inconvenience and with best regards,
Natsuhiko

**Comment by alperoglu** [comment]
Hi Natsuhiko,

I just downloaded and compiled them. Its currently working and giving the correct outputs that @adamturner1 shared for the bulk samples. Thank you very much for reaching out and solving this problem.

Take care,
Alper
