### ISSUE TITLE
First row of RASQUAL output

### ISSUE THREAD

**Issue by adamturner1** [natsuhiko/rasqual#46]
Hi Natsuhiko,

RASQUAL has been helpful so far for caQTL analysis and ATAC-seq data. It seems to be working when I use a wrapper script to run RASQUAL on all peaks in our dataset. However, I get 1.000000, 1.000000, etc. all across the first row of each output file (I attached a picture of what I get). The rest of the output all looks correct according to the **Output** section in the tutorial. I've tried a lot of things but always get this in the output.

![rasqual_output](https://user-images.githubusercontent.com/35438715/106397704-b248c300-63dc-11eb-9daa-84be732e1b06.png)

Do you think is due to some memory issue or something else? Also I assume this would not affect our results?

Any help would be much appreciated.

Thank you!
Adam

**Comment by natsuhiko** [comment]
Hi Adam,

Could you also paste the command you typed here?

Best regards,
Natsuhiko

**Comment by adamturner1** [comment]
Hi Natsuhiko,

I use a wrapper script as follows:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/35438715/115892136-de487300-a424-11eb-9ad6-40edb3ab7397.png">

The rasqual command I use is:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/35438715/115894596-72b3d500-a427-11eb-8ea3-f40f6759e6ca.png">

Apologies if this is a lot of lines. I used rasqualTools to prepare the input files. The 'exon_start_positions' and 'exon_end_positions' correspond to the start and end of each ATAC-seq peak. If I run RASQUAL on a feature (ATAC-seq peak) individually I don't get this error. Since I have thousands of ATAC-seq peaks I have to use the above commands but unfortunately keep on getting 1.000000, 1.000000, etc. and have not figured it out.

Thank you for your help!

Best regards,
Adam

**Comment by natsuhiko** [comment]
Hi Adam,

If you remove `-v` option in the second last line of the above screen shot, what will happen?

Best regards,
Natsuhiko

**Comment by natsuhiko** [comment]
Hi Adam,

I modified the verbose level so that you won't see this line with `-v` option. Sorry for the inconvenience.

Best regards,
Natsuhiko

**Comment by adamturner1** [comment]
Hi Natsuhiko,

Thank you for this!

Best,
Adam
