### ISSUE TITLE
Identical results for close SNP

### ISSUE THREAD

**Issue by Zepeng-Mu** [natsuhiko/rasqual#47]
Hi, I noticed that in my RASQUAL results, there are many cases for SNPs that are close to each other to have identical results, except for their SNP ID, REF and ALT columns. I am wondering whether this suggests there are some problems with the RASQUAL run, or is this to be expected?

Thanks so much in advance!

**Comment by kauralasoo** [comment]
Have you checked if these variants are in perfect LD i.e. their genotype values are perfectly correlated? If that's the case, then you would expect to see identical results.

**Comment by Zepeng-Mu** [comment]
Hi, thanks for the quick response! I checked one case and indeed the SNPs are in perfect LD.
