### ISSUE TITLE
Estimated computation time too long

### ISSUE THREAD

**Issue by liesaweigert** [natsuhiko/rasqual#48]
I am currently using rasqual for ATAC data with features extended 50 000kb around each peak. Unfortunately for most of the features the computation is canceled, because the estimated computation time is too long. 

Estimated computational time is too long for 8:29443453:29544444 (Sample Size=84, NofrSNPs=249, NoffSNPs=215)...aborted.
Estimated computational time is too long for 8:29466273:29567135 (Sample Size=84, NofrSNPs=233, NoffSNPs=200)...aborted.
Estimated computational time is too long for 8:29472642:29573108 (Sample Size=84, NofrSNPs=227, NoffSNPs=191)...aborted.
Estimated computational time is too long for 8:29530196:29630965 (Sample Size=84, NofrSNPs=210, NoffSNPs=185)...aborted.
Estimated computational time is too long for 8:29544525:29645849 (Sample Size=84, NofrSNPs=201, NoffSNPs=185)...aborted.
Estimated computational time is too long for 8:29607788:29708459 (Sample Size=84, NofrSNPs=195, NoffSNPs=180)...aborted.
Estimated computational time is too long for 8:29611621:29712319 (Sample Size=84, NofrSNPs=198, NoffSNPs=183)...aborted.

Is there a way to fix this or somehow parallalize the computation?

**Comment by natsuhiko** [comment]
Hi,

You can set '--force' option to ignore this warning. You can also parallelise the computation by set '--n-threads' option.

Although it seems the number of feature SNPs is too many. For ATAC-seq, we usually see 3-4 SNPs per peak. I would recommend to revise your command first.

Natsuhiko
